### ISSUE TITLE
Hand drawing 使用者流程圖

### ISSUE THREAD

**Issue by bluet** [0verseas/0verStudent#1]
- [x] 首頁
- [x] 申請帳號
- [x] 登入
- [x] 基本資料
   - 學歷
- [x] 選填志願
- [ ] 列出須繳交資料（請使用者寄送）
- [ ] 上傳備審資料

Expected output: Text + graph document

**Comment by sunnyworm** [comment]
https://drive.google.com/a/mail.ncnu.edu.tw/file/d/0B539csY6QL2IU0c0TENhdGxlOWc/view?usp=sharing
