### ISSUE TITLE
新增備用 email (選填)

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verStudent#20]

**Comment by lemon5920** [comment]
[d3cd4df](https://github.com/0verseas/0verStudent/commit/d3cd4df8bcfd3022e197f90102cc23a76f5b76ea)

**Comment by lemon5920** [comment]
![螢幕快照 2017-09-26 下午6.15.31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56f3c631af145f0e006a6252/125516c66e82c728ace21e0d46606a58a65b762c502238a6631da2c478116a237049f17d30013bc33aaf9357415e4bb242594d58eeb9cb74fce36f34985619e8d83f0d73c26c43fdbe8b1eb754ba208a1cd3e5b8dc4cc4fa2137a5dad11b61435c52dcbd4f3fb2984dc259f34be74957a41a3261e771336e0a.png)
