### ISSUE TITLE
入學時間與畢業時間有年份月份即可，不用到日

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verStudent#21]

**Comment by lemon5920** [comment]
[0e354a8](https://github.com/0verseas/0verStudent/commit/0e354a8ce4d1dd2a8cf9bc2afe03613c915ee14a)

**Comment by lemon5920** [comment]
![螢幕快照 2017-09-26 下午6.11.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56f3c631af145f0e006a6252/125516c66e82c728ace21e0d46606a58a65b762c502238a6631da2c478116a237049f17d30013bc33aaf9357415e4fb2425c4d58eeb9cb74fce36f34985619e8d83f0d73c26c43fdbe8b1eb754ba208a1cd3e5b8dc4cc4fa2137a5dad11b61435c52dcbd4f3fb2984dc259f34be74957a4143767e07e346e0a.png)
