### ISSUE TITLE
港二技-個人基本資料需新增欄位

### ISSUE THREAD

**Issue by hewen-lotus** [0verseas/0verStudent#33]
最高學歷欄位下新增
1. 文憑類別(副學士學位或高級文憑選單)
2. 課程名稱(手填)
3. 課程認可期限(開始與結束日期) （要注意結束日期需包含永久有效）

**Comment by lemon5920** [comment]
請提供
1. 每個欄位對應到後端的 key (儲存與渲染用)
2. 每個欄位是必填 / 選填
3. 不清楚「包含永久有效」的意思

**Comment by hewen-lotus** [comment]
港二技文憑類別:  two_year_tech_diploma( 1. 副學士學位 2. 高級文憑選單) / 必填
港二技課程名稱:  two_year_tech_class_name / 必填
港二技課程開始日期: two_year_tech_class_start / 必填
港二技課程結束日期: two_year_tech_class_end / 選填
