### ISSUE TITLE
馬來西亞獨中生目前沒有聯分採計可以選

### ISSUE THREAD

**Issue by hewen-lotus** [0verseas/0verStudent#40]
建議新增以下選項：
1. 以華文獨中統考文憑申請第二梯次，僅限分發臺師大僑先部
2. 以 STPM 文憑申請 (或 A Level 文憑申請者)
3. 以 SPM 文憑申請 (或 S.A.P、Pernyataan、O Level)

**Comment by lemon5920** [comment]
可選的成績採計方式 不是在前端控制的
前端是依照後端給的選項渲染而已。
