### ISSUE TITLE
僑居地ID 港、澳 在旁邊給範例

### ISSUE THREAD

**Issue by hewen-lotus** [0verseas/0verStudent#43]

**Comment by zxp86021** [comment]
這個後端可以驗證喔^^

**Comment by hewen-lotus** [comment]
香港： A123456(7)
澳門：1234567
其他地區：不管

**Comment by zxp86021** [comment]
API 驗證 https://github.com/0verseas/0verAPI/commit/8f4818ac39e978d2ca4b96a6d1969fd36eaff290
只驗證格式，沒有驗證正確性
另外香港未來會變成雙英文字母開頭，也已經加上去了

**Comment by zxp86021** [comment]
香港身份證 ref: https://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E8%BA%AB%E4%BB%BD%E8%AD%89

**Comment by zxp86021** [comment]
前端新增 https://github.com/0verseas/0verStudent/commit/9fe45f4996753c1aca2f9e4f2bd4164e1a3aabc1
