### ISSUE TITLE
聯合分發選填志願的頁面要加上說明文字，使學生清楚知道現在填的是聯合分發志願

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verStudent#7]

**Comment by lemon5920** [comment]
[0d9cda8](https://github.com/0verseas/0verStudent/commit/0d9cda8ce24467ccb6d5c985ade532393bc016b3)

**Comment by lemon5920** [comment]
每個頁面都加上如下圖的大標題
![螢幕快照 2017-09-26 下午6.01.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56f3c631af145f0e006a6252/125516c66e82c728ace21e0d46606a58a65b762c502238a6631da2c478116a237049f17d30013bc33aaf9357415f4fb2445e4d58eeb9cb74fce36f34985619e8d83f0d73c26c43fdbe8b1eb754ba208a1cd3e5b8dc4cc4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be74957a4123367e37f316e0a.png)
