### ISSUE TITLE
選填志願頁面查詢校系清單的方式要有查詢校名、系名、學群、志願代碼

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verStudent#9]

**Comment by lemon5920** [comment]
缺學群。

**Comment by lemon5920** [comment]
[9dccfdb](https://github.com/0verseas/0verStudent/commit/9dccfdb9f82571f34ece5401620d54a0aec6ed7a)

**Comment by lemon5920** [comment]
「奧林匹亞志願」、「個人申請志願」、「聯合分發志願」皆有「校名」、「系名」、「學群」、「志願代碼」篩選類別
![螢幕快照 2017-09-26 下午6.03.39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56f3c631af145f0e006a6252/125516c66e82c728ace21e0d46606a58a65b762c502238a6631da2c478116a237049f17d30013bc33aaf9357415f4db242514d58eeb9cb74fce36f34985619e8d83f0d73c26c43fdbe8b1eb754ba208a1cd3e5b8dc4cc4fa2137a5dad11b61435c52dcbd4f3fb29842c259f34be74957a410326be576316e0a.png)
